### ISSUE TITLE
Why Babel as build choice?

### ISSUE THREAD

**Issue by djasnowski** [HorusGoul/node-ts-starter#5]
Great stuff. What I've been looking for. Just a question -- why babel? When we have parcel and snowpack which seem to fair better?

**Comment by HorusGoul** [comment]
I decided to go with Babel for this starter because of its ecosystem. Other transpilers such as `swc` or `esbuild` are great but don't have many plugins or documentation available yet.

Regarding bundlers, the purpose of this starter is to avoid worrying about configuring a bundler, you can use it until you need one, and when that moment arrives, you'll notice it. Adding a bundler on top of this configuration is easy, as you only need to hook it up with the Babel and TypeScript settings.

Thanks!
